const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('maplebot', {
  getGuides: () => ipcRenderer.invoke('get-guides'),
  saveUserGuides: (guides) => ipcRenderer.invoke('save-user-guides', guides),
  getDatabase: () => ipcRenderer.invoke('get-database'),
  getDisplays: () => ipcRenderer.invoke('get-displays'),
  setOpacity: (v) => ipcRenderer.send('set-opacity', v),
  setAlwaysOnTopLevel: (level) => ipcRenderer.send('set-always-on-top-level', level),
  toggleLock: () => ipcRenderer.send('toggle-lock'),
  setCollapsed: (collapsed, height) => ipcRenderer.send('set-collapsed', collapsed, height),
  minimizeToTray: () => ipcRenderer.send('minimize-to-tray'),
  quit: () => ipcRenderer.send('quit-app'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  onLockChanged: (cb) => ipcRenderer.on('lock-changed', (_e, locked) => cb(locked)),
  onHotkey: (cb) => ipcRenderer.on('hotkey', (_e, action) => cb(action)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_e, info) => cb(info)),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (_e, pct) => cb(pct)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', (_e, info) => cb(info)),
  onUpdateError: (cb) => ipcRenderer.on('update-error', (_e, msg) => cb(msg)),
  downloadUpdate: () => ipcRenderer.invoke('update-download'),
  installUpdate: () => ipcRenderer.invoke('update-install'),
  checkForUpdates: () => ipcRenderer.invoke('update-check'),
  startOCR: () => ipcRenderer.invoke('ocr-start'),
  stopOCR: () => ipcRenderer.invoke('ocr-stop'),
  getOCRStatus: () => ipcRenderer.invoke('ocr-status'),
  getOCRSettings: () => ipcRenderer.invoke('ocr-get-settings'),
  setOCRSettings: (s) => ipcRenderer.invoke('ocr-set-settings', s),
  onOCRStatusChanged: (cb) => ipcRenderer.on('ocr-status-changed', (_e, s) => cb(s)),
  onOCRResult: (cb) => ipcRenderer.on('ocr-result', (_e, r) => cb(r)),
  getOCRConfig: () => ipcRenderer.invoke('ocr-get-config'),
  previewOCR: () => ipcRenderer.invoke('ocr-preview'),
  calibrateOCR: (displayId) => ipcRenderer.send('ocr-calibrate', displayId),
  exportGuides: (payload) => ipcRenderer.invoke('export-guides', payload),
  importGuides: () => ipcRenderer.invoke('import-guides'),
  exportProfile: (p) => ipcRenderer.invoke('export-profile', p),
  importProfile: () => ipcRenderer.invoke('import-profile'),
  saveOCRCalibration: (rect) => ipcRenderer.invoke('ocr-save-config', rect),
  cancelOCRCalibration: () => ipcRenderer.send('ocr-calibrate-cancel')
});
